#preprocess:
#  - 
datasets:
  - p4_dox_2026
labels:
  - senescent
  - control

train:
  learning_rate: 0.001
  batch_size: 16
  num_epochs: 20
segment:
  learning_rate: 0.001
  batch_size: 16
  num_epochs: 20
maskpredict:
  learning_rate: 0.001
  batch_size: 16
  num_epochs: 20